language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - extra-android-support
    - tools
    - build-tools-24.0.2
    - android-24
    - sys-img-x86-android-24
    - sys-img-armeabi-v7a-android-24


before_install:
  - echo yes | android update sdk -a --filter platform-tools --no-ui --force

script:
  - ./gradlew clean assembleVanillaDebug -PdisablePreDex
  - ./gradlew check || (grep -A20 -B2 'severity="Error"' WordPress/build/outputs/lint-results-vanillaDebug.xml; exit 1)
