language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - sys-img-x86-android-23

env:
   global:
      - MALLOC_ARENA_MAX=2
      - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
      - ANDROID_SDKS=android-24
      - ANDROID_TARGET=android-24

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi x86
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean assembleDebug
  - ./gradlew check connectedCheck