language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - sys-img-x86-android-24
    - sys-img-armeabi-v7a-android-24

script:
  - ./gradlew clean assembleDebug
  - ./gradlew check 