language: android
jdk: oraclejdk8

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - sys-img-x86-android-23

env:
   global:
      - MALLOC_ARENA_MAX=2
      - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
      - ANDROID_SDKS=android-14
      - ANDROID_TARGET=android-14

install:
  # Setup gradle.properties
  - cp WordPress/gradle.properties

script:
  - ./gradlew clean assembleDebug
  - ./gradlew check connectedCheck